/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Omar_Mohamed (https://sketchfab.com/Omar_Mohamed)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/airplane-628232dd846249f6a89ed3fb2e1cd4f5
title: Airplane
*/

import React, { useRef } from "react";
import { a } from "@react-spring/three";
import { useGLTF, useAnimations } from "@react-three/drei";

function AirplaneModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/airplane/airplane.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <a.group
      scale={0.01}
      rotation={[Math.PI / 2, 0, 0]}
      ref={group}
      // position={[0, 0, 1.2]}
      position={props.position}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="cbdb2b201266454e947bf115439508aefbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Cylinder" position={[0, 0, 0]} scale={1}>
                  <group name="Cylinder001" position={[0, 0, 1.8]} scale={0.3}>
                    <mesh
                      name="Cylinder001_Material005_0"
                      geometry={nodes.Cylinder001_Material005_0.geometry}
                      material={materials["Material.005"]}
                    />
                    <mesh
                      name="Cylinder001_Material003_0"
                      geometry={nodes.Cylinder001_Material003_0.geometry}
                      material={materials["Material.003"]}
                    />
                  </group>
                  <mesh
                    name="Cylinder_Material003_0"
                    geometry={nodes.Cylinder_Material003_0.geometry}
                    material={materials["Material.003"]}
                  />
                  <mesh
                    name="Cylinder_Material001_0"
                    geometry={nodes.Cylinder_Material001_0.geometry}
                    material={materials["Material.001"]}
                  />
                  <mesh
                    name="Cylinder_Material002_0"
                    geometry={nodes.Cylinder_Material002_0.geometry}
                    material={materials["Material.002"]}
                  />
                  <mesh
                    name="Cylinder_Material004_0"
                    geometry={nodes.Cylinder_Material004_0.geometry}
                    material={materials["Material.004"]}
                  />
                </group>
                <group
                  name="Point"
                  position={[487.22, 868.26, 779]}
                  scale={100}
                >
                  <group name="Object_13" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_14" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

useGLTF.preload("/airplane/airplane.gltf");

export default AirplaneModel;
